#!/bin/bash -l

#Submit this script with: sbatch thefilename
#SBATCH --output=submitshell.out
#SBATCH --time=100:00:00   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=5G   # memory per CPU core
#SBATCH --mail-user=jpr57@cam.ac.uk   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL


python FinalL96.py ${NOISE} ${STD}
