#!/bin/bash -l

#Submit this script with: sbatch thefilename
#SBATCH --output=GPMCMC.out
#SBATCH --time=5:00:00   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=10G   # memory per CPU core
#SBATCH --mail-user=jpr57@cam.ac.uk   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL


python2.7 -u  CombinedTrainMCMC.py
