#!/bin/bash -l

#Submit this script with: sbatch thefilename
#SBATCH --job-name=arrayJob
#SBATCH --output=/home/jprosser/Documents/WorkPlacements/Caltech/Code/ARRAY/arrayJob_%A_%a.out
#SBATCH --array=5-205
#SBATCH --time=168:00:00
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=1G   # memory per CPU core

#echo "My SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID

python2.7 -u  MCMCL96array.py $SLURM_ARRAY_TASK_ID
